### ISSUE TITLE
Labels not translated anymore

### ISSUE THREAD

**Issue by nicoonee** [gwendall/meteor-autoform-i18n#1]
Commit 8d68cfb@gwendall fixed for default values 

acctualy breaks label translation

https://github.com/gwendall/meteor-autoform-i18n/blob/master/shared/lib.js#L16
removing schema[key].label || from before clousure make it works again.
Quick fix would be nice ;)

**Comment by gwendall** [comment]
What sort of error are you getting?

**Comment by nicoonee** [comment]
no errors just labels not translated

**Comment by gwendall** [comment]
This is by design. If you explicitely define a label in your schema, the package will not overwrite it with the data it may find in your i18n files. Do not declare any label in your schema for the package to translate it. I will document that more.
